### PR TITLE
fix issues/82

### PR DESCRIPTION
**Pull request by zhangchunzhong**
first time to commit a rust code, please feel freely to give comments.Thanks in advance!

### CODE REVIEW

**Review by panarch — CHANGES_REQUESTED** [review]
So welcome of your first pr, thanks :)

Most of changes basically look good and I want to request small changes.
`blend.rs` has some confusing codes but you did well.
Let us begin with explaining background story on this.
What `blend.rs` does is this,
In `SELECT a, b, c FROM Foo;`
Using fetched rows from `Foo` table, in `GlueSQL` we call it as `Context`.
`blend.rs` consumes `Context` and extracts only specified columns `a, b, c`.

To make that work, as you saw `blend` parses `SelectItem`.
Though there certainly exists a module named `evalute` which takes borrowed `Context` as a param and return evaluated value, `blend.rs` `blend` function works in a little bit different way.
`evaluate` works by `clone` value from `Context`.
When we run simple `blend` work, like `a, b, c`, we actually don't need to `clone`, we can simply take ownership of that value from `Context`.
Some customized code in `blend.rs` is all for avoiding unnecessary `clone` calls.
That optimizations are only applied for simple identifiers.
Complex ones like `Expr::BinaryOp { .. } | Expr::Function(_)`, `blend` simply calls `evaluate`.

----

Now the review part.

1. Currently there are too many separated commits, can you reduce into two commits?
May be you need to use force push on this.

* The changes you made on `src/data/value.rs`
Thanks for doing this stuff, and this is independent from main work so it looks better to split into a different commit.
* And all other changes

2. Rather than mentioning an issue number, please change to use sentence format with description

Though you don't need to write too many details, It's required to be recognizable without opening the issue page.

3. Merging `SelectItem::ExprWithAlias` into `SelectItem::UnnamedExpr`

`match` in Rust is so.. beautifully powerful.
No redundant codes are required.
You can actually use like this below,
```rust
SelectItem::UnnamedExpr(expr) |
SelectItem::ExprWithAlias { expr, .. } => match expr {
..
```

And also you don't need to specify unused identifiers,
```rust
Expr::BinaryOp { left: _, op: _, right: _ }

// It is enough to use this
Expr::BinaryOp { .. }
```

4. Adding `AS` test cases to `src/tests/blend.rs` can be enough

I think it's too much to have separate test cases only for this aliased expressions.
Can you remove `select_as.rs` then add test cases using `AS` in `src/tests/blend.rs`?

---
Please feel free to mention back anything you need more, thanks 👍

**Comment by zhangchunzhong** [comment]
The changes made on src/data/value.rs is just to pass the "cargo clippy" in github action:
https://github.com/gluesql/gluesql/pull/96/commits/0357243125ad64bf344f0aedb976a80f4b09e835

**Comment by panarch** [comment]
@zhangchunzhong Yes, that's right. It's just because changes are made by https://github.com/gluesql/gluesql/pull/96/commits/0357243125ad64bf344f0aedb976a80f4b09e835 and https://github.com/gluesql/gluesql/pull/96/commits/858de2ed67d98207f756a689e046dd8c6bd4b5a9

**Comment by panarch** [comment]
resolve #82

**Comment by panarch** [comment]
@zhangchunzhong Thanks! merging

**Pull request merged**
