### PR TITLE
chore:[#700] rust version update

### LINKED ISSUE #700: Rust version update - 1.62
## Description
While doing the #699 , I found that [rust version 1.62 is released](https://blog.rust-lang.org/2022/07/19/Rust-1.62.1.html) recently.

### clippy status
clippy seems to be [released 1.62.0](https://github.com/rust-lang/rust-clippy/releases/tag/rust-1.62.0)

### some clippy warnings
With 1.62 setting, I found some `clippy` warnings. It would be nice to resolve when updating the rust lang version
- macro related warnings
  - [github action link](https://github.com/24seconds/gluesql/runs/7596519405?check_suite_focus=true)
  - [clippy explanation](https://rust-lang.github.io/rust-clippy/master/index.html#crate_in_macro_def)
- unused lifetime
  - [github action link](https://github.com/24seconds/gluesql/runs/7596198969?check_suite_focus=true )

### note
I saw there is a good pr related to this - #564 .

### PR DESCRIPTION
**Pull request by ChobobDev**
resolves #700 

I tried running `cargo build` on my environment and the build was completed without an error.

If I have missed something please let me know.

many thanks

### CODE REVIEW

**Comment by devgony** [comment]
If you click failed action, you could find commands like
```
  cd core
  cargo clippy --no-default-features -- -D warnings
  cargo clippy --no-default-features --features metadata -- -D warnings
  cargo clippy --no-default-features --features alter-table -- -D warnings
  cargo clippy --no-default-features --features index -- -D warnings
  cargo clippy --no-default-features --features transaction -- -D warnings
  cargo clippy --no-default-features --features "alter-table index" -- -D warnings
  cargo clippy --no-default-features --features "alter-table transaction" -- -D warnings
  cargo clippy --no-default-features --features "index transaction" -- -D warnings
  cargo clippy --no-default-features --features "alter-table index transaction" -- -D warnings
  cargo clippy --all-features --all-targets -- -D warnings
```
It should pass these commands.

To work faster, you can execute these commands on your local environment as well

**Review by devgony — CHANGES_REQUESTED** [review]
If you click failed action, you could find commands like

  cd core
  cargo clippy --no-default-features -- -D warnings
  cargo clippy --no-default-features --features metadata -- -D warnings
  cargo clippy --no-default-features --features alter-table -- -D warnings
  cargo clippy --no-default-features --features index -- -D warnings
  cargo clippy --no-default-features --features transaction -- -D warnings
  cargo clippy --no-default-features --features "alter-table index" -- -D warnings
  cargo clippy --no-default-features --features "alter-table transaction" -- -D warnings
  cargo clippy --no-default-features --features "index transaction" -- -D warnings
  cargo clippy --no-default-features --features "alter-table index transaction" -- -D warnings
  cargo clippy --all-features --all-targets -- -D warnings
It should pass these commands.

To work faster, you can execute these commands on your local environment as well.

**Comment by ChobobDev** [comment]
I first tried to change the `clippy lint`  as the error from the GitHub action guided me. 
Thank you for letting me know the commands I can run on the local environment. 
I will check those and solve the lint error that clippy gives me

Many thanks

**Comment by ChobobDev** [comment]
- [x] cargo clippy --no-default-features -- -D warnings
- [ ] cargo clippy --no-default-features --features metadata -- -D warnings
- [ ] cargo clippy --no-default-features --features alter-table -- -D warnings
- [ ] cargo clippy --no-default-features --features index -- -D warnings
- [ ] cargo clippy --no-default-features --features transaction -- -D warnings
- [ ] cargo clippy --no-default-features --features "alter-table index" -- -D warnings
- [ ] cargo clippy --no-default-features --features "alter-table transaction" -- -D warnings
- [ ] cargo clippy --no-default-features --features "index transaction" -- -D warnings
- [ ] cargo clippy --no-default-features --features "alter-table index transaction" -- -D warnings
- [ ] cargo clippy --all-features --all-targets -- -D warnings

**Review by panarch — APPROVED** [review]
Clippy becomes more smarter, looks all good. Thanks a lot!

**Pull request merged**
