### PR TITLE
AUTO_INCREMENT

### PR DESCRIPTION
**Pull request by KyGost**
Relates: #159

### CODE REVIEW

**Comment by KyGost** [comment]
Quite yuck and not yet working for rows inserted without `NULL` but working nonetheless.

@panarch how do you feel about giving `StoreMut` to `Execute::prepare` and `Row::new`?

**Comment by panarch** [comment]
@KyGost 
1. `Execute::prepare`
I actually think `Execute::prepare` is... not meaningful to keep, first intention was dividing `Store` uses and `Store + StoreMut` uses but now I'm not sure that is really meaningful.
It might be better to re-combine `prepare` and `execute`, how do you think?

2. `Row::new`
You mean that providing `Store` to `Row::new`? then I think it would be good to keep `data` modules not to depend on `Store`. making it lightweight, containing "data" and some useful utility methods.

**Comment by KyGost** [comment]
@panarch 
> 1. `Execute::prepare`
>    I actually think `Execute::prepare` is... not meaningful to keep, first intention was dividing `Store` uses and `Store + StoreMut` uses but now I'm not sure that is really meaningful.
>    It might be better to re-combine `prepare` and `execute`, how do you think?

That sounds like a good idea.


> 2. `Row::new`
>    You mean that providing `Store` to `Row::new`? then I think it would be good to keep `data` modules not to depend on `Store`. making it lightweight, containing "data" and some useful utility methods.

Yup. I agree, it felt off to give it. How would you suggest it be done?
I need to run a `tree.get` & `tree.set` for each row.

**Comment by KyGost** [comment]
resolve #159

**Pull request closed without merging**
