### PR TITLE
ci: Automatically assign a PR to its author

### LINKED ISSUE #667: Add Assignees automatically when someone creates PR
## Description

Currently in the gluesql when the PR is created by someone - let say Bob, then gluesql maintainers manually assign the Bob as `Assignees` section - which is quite cumbersome. So it is good to let bot add assignees. I remember there was a github action which exactly supports this.

### PR DESCRIPTION
**Pull request by rapsealk**
This PR resolves #667, using a well-known GitHub Actions workflow [toshimaru/auto-author-assign](https://github.com/toshimaru/auto-author-assign).

Please refer [this](https://github.com/rapsealk/github-actions-swing/pull/1) to see how it will work.

### CODE REVIEW

**Comment by ever0de** [comment]
Maybe you could consider [kentaro-m/auto-assign-action](https://github.com/kentaro-m/auto-assign-action)?
It's not a huge difference, but it has additional features like assigning reviewers, etc. and it seems like a reasonable choice for maintenance to use the workflow that has more users.
What do you think?

**Comment by rapsealk** [comment]
@ever0de Update completed. Please refer [this](https://github.com/rapsealk/github-actions-swing/pull/2) to see how it works.

**Review by ever0de — APPROVED** [review]
That's good 👍, Now we don't have to specify it manually, which is nice 😃

**Review by panarch — APPROVED** [review]
That looks really good! Thanks a lot for the contribution 👍 👍

**Review by devgony — APPROVED** [review]

**Pull request merged**
