### PR TITLE
Add Documentation

### PR DESCRIPTION
**Pull request by KyGost**
WIP

### CODE REVIEW

**Comment by KyGost** [comment]
Looks like I already had a draft PR.

What needs to be added before merge?
Sorry it has been sitting here for so long.

**Review by panarch — CHANGES_REQUESTED** [review]
Again, please feel free to participate :)
And wow you also added an error guideline, thanks so much!

Looks very good to start!

There is an one stuff I request you to change,
Because of end-of-line issue, GitHub Action failed on `cargo fmt`

Then, I'll merge this and make it accessible via https://gluesql.org/book

I'm considering to use https://github.com/marketplace/actions/mdbook-action to automate

**Comment by KyGost** [comment]
@panarch thoughts on what to do about this check error?

**Comment by panarch** [comment]
@KyGost It would be the issue of your editor. `cargo fmt` doesn't solve this? then.. I think editing those files in github.com web editor might work.

**Comment by KyGost** [comment]
@panarch rustfmt worked this time but the tests failed because of the example code, have a look at the fail details.

**Comment by panarch** [comment]
@KyGost Ok, I think I got it if.. you are using Windows.

Can you try `cargo fmt` again after adding file with `rustfmt.toml` to the root of the repository?

In `rustfmt.toml`,
```toml
newline_style = "Unix"
```

**Comment by KyGost** [comment]
The issue coming up when I check the error on the commit is:
```
error[E0432]: unresolved imports `gluesql::Glue`, `gluesql::SledStorage`
 --> examples/hello_world.rs:1:22
  |
1 | use gluesql::{parse, Glue, Payload, SledStorage, Value};
  |                      ^^^^           ^^^^^^^^^^^ no `SledStorage` in the root
  |                      |
  |                      no `Glue` in the root
  |                      help: a similar name exists in the module: `glue`
```

**Comment by panarch** [comment]
@KyGost ok, I can say what's going on in here.

> The issue coming up when I check the error on the commit is:
> 
> ```
> error[E0432]: unresolved imports `gluesql::Glue`, `gluesql::SledStorage`
>  --> examples/hello_world.rs:1:22
>   |
> 1 | use gluesql::{parse, Glue, Payload, SledStorage, Value};
>   |                      ^^^^           ^^^^^^^^^^^ no `SledStorage` in the root
>   |                      |
>   |                      no `Glue` in the root
>   |                      help: a similar name exists in the module: `glue`
> ```

`gluesql::Glue` and `gluesql::SledStorage` are exported only if `sled_storage` feature is enabled.
These are optional because it is not required for making a custom storage, only useful for standalone use.

In `Cargo.toml`,
image

For convenience, I enabled `sled_storage` feature by default.
So, someone who simply wants to use GlueSQL like SQLite, they can import and use it based on `SledStorage`. They don't need to care anything about features.
However, for custom storage makers who doesn't need `SledStorage`, they can import `gluesql` with `sled_storage` disabled.

And tests should work both with features & without features.
In [.github/workflows/rust.yml](https://github.com/gluesql/gluesql/blob/main/.github/workflows/rust.yml)
image

I included several `cargo test` cases.
without features, using `sled_storage`, using `alter_table`, and using both `sled_storage` and `alter_table`.

Your examples require `sled_storage` feature, so you need to use `cfg` macro.

Style is up to you.
If you change your example file like this below, then it will not make noise.
https://gist.github.com/panarch/48bf217c46938ca6484eea9f6d649956
or you can see `examples/api_usage.rs` or `examples/using_config.rs`.

**Comment by KyGost** [comment]
@panarch ahhh okay, thank you very much.

Something different seems to have failed now though...? :-(

**Comment by panarch** [comment]
@KyGost 👍
I think your last commit will also fail.
`#[cfg(feature = "sled-storage")]` this is only applied to the next line.

fyi. https://doc.rust-lang.org/reference/attributes.html

So, in `examples/hello_world.rs`
```rust
#[cfg(feature = "sled-storage")]
use gluesql::{parse, Glue, Payload, SledStorage, Value};	use gluesql::{parse, Glue, Payload, SledStorage, Value};
```

It only excludes `use` line but those are used in `fn main() { ... }` so it cannot be compiled.

**Comment by KyGost** [comment]
Oh I see, I need to use
```rust
#[cfg(feature = "sled-storage")]
mod sled_multi_threaded {
...
}
```

Thanks

**Comment by KyGost** [comment]
@panarch it should work now but now includes needless items in the book. How can we avoid this? Is there a way to add the rules to the file outside of the file?
image

**Comment by KyGost** [comment]
Looks like it failed again....

**Comment by panarch** [comment]
> Looks like it failed again....
> 
> Was the strictness increased recently?
> Looks like it is failing on other `~/executor/` things, which haven't been changed in this PR and should have passed previously.

Oh, I just tested and found that. I'm simply using the default setting of clippy, it looks like it is because of recent `cargo` updates.
I'll take this and make it lint-clean again till tomorrow, then I'll merge to `main` then please merge this to this branch. Then GitHub Action `cargo clippy` will pass.

**Comment by panarch** [comment]
> @panarch it should work now but now includes needless items in the book. How can we avoid this? Is there a way to add the rules to the file outside of the file?
> image

That make sense.
I also need to figure out the way to make it better.

We might solve this by editing `Cargo.toml`.
If we can make cargo to ignore `examples/` when `sled_storage` feature is disabled, then it would be cool.

Let me know you found something, I'll also try to figure out.

**Comment by panarch** [comment]
@KyGost https://github.com/gluesql/gluesql/pull/142
Tomorrow is too far from now.
Now `main` branch is clippy clean :)
Please merge and try again 👍

**Comment by KyGost** [comment]
> @KyGost #142
> Tomorrow is too far from now.
> Now `main` branch is clippy clean :)
> Please merge and try again 👍

Awesome! I'll rebase.

**Comment by KyGost** [comment]
@panarch woohoo! Tests passed.

**Review by panarch — APPROVED** [review]
@KyGost Awesome 👍 👍 👍 
I'll merge and build & upload to https://gluesql.org/book soon!

About making this implicitly, let's do it in another pr.
image

Thanks!!

**Review by panarch — APPROVED** [review]
@KyGost Awesome 👍 👍 👍 
I'll merge and build & upload to https://gluesql.org/book soon!

About making this implicitly, let's do it in another pr.
image

Thanks!!

**Pull request merged**
