### PR TITLE
[RFC] Feature/func bit not

### PR DESCRIPTION
**Pull request by gurugio**
Just a draft PR to check the test coverage.

I don't write full description for each patch because I don't understand well 
what ast, ast_builder, evaluator, executor, plan and translate do and how they co-operate.
I will add description later.

I will add more test cases to increase the test coverage.
- Creating a table and run bit_not function and operator with the values in the table

### CODE REVIEW

**Comment by panarch** [comment]
though it does not need to be well written, it would be better to use english for all others to understand the pr content.
could you write the pr description in english?

**Review by devgony — COMMENTED** [review]
Could you please run `cargo fmt`?
Or you could install `rust-analyzer` and use `format on save`

**Comment by panarch** [comment]
```rust
pub enum UnaryOperator {
    Plus,
    Minus,
    Not,
    /// Bitwise Not, e.g. `~9` (PostgreSQL-specific)
    PGBitwiseNot,
    /// Square root, e.g. `|/9` (PostgreSQL-specific)
    PGSquareRoot,
    ..
}
```
It looks that sqlparser-rs supports bitwise not operator using `~` symbol.
could we consider to use this rather than adding as a function?

ref.
https://github.com/sqlparser-rs/sqlparser-rs/blob/a50671d95d34688529fbc3d4452bec164ff21497/src/ast/operator.rs#L30C17-L46

**Comment by gurugio** [comment]
> though it does not need to be well written, it would be better to use english for all others to understand the pr content. could you write the pr description in english?

Sure.

**Comment by gurugio** [comment]
> ```rust
> pub enum UnaryOperator {
>     Plus,
>     Minus,
>     Not,
>     /// Bitwise Not, e.g. `~9` (PostgreSQL-specific)
>     PGBitwiseNot,
>     /// Square root, e.g. `|/9` (PostgreSQL-specific)
>     PGSquareRoot,
>     ..
> }
> ```
> 
> It looks that sqlparser-rs supports bitwise not operator using `~` symbol. could we consider to use this rather than adding as a function?
> 
> ref. https://github.com/sqlparser-rs/sqlparser-rs/blob/a50671d95d34688529fbc3d4452bec164ff21497/src/ast/operator.rs#L30C17-L46

Yes, I will add operator.
I thought the sqlparser-rs does not support that operator.

One question.
Do you think it would be better to add only operator?
Or both of operator and function?

**Comment by panarch** [comment]
> One question.
Do you think it would be better to add only operator?
Or both of operator and function?

Let's make it simple for this PR :)
It would be good enough for only having an operator.

**Comment by devgony** [comment]
> > Could you please run `cargo fmt`? Or you could install `rust-analyzer` and use `format on save`
> 
> Sure, thank you for your review. Actually I already have been using the rust-analyzer in the vscode. I don't understand why there is mis-formatted code but will double-check for next PR.

You could try in VSCode: Settings (ctrl + ,) > search "format on save" > enable

**Comment by gurugio** [comment]
> > One question.
> > Do you think it would be better to add only operator?
> > Or both of operator and function?
> 
> Let's make it simple for this PR :) It would be good enough for only having an operator.

Got it.

**Comment by gurugio** [comment]
> > > Could you please run `cargo fmt`? Or you could install `rust-analyzer` and use `format on save`
> > 
> > 
> > Sure, thank you for your review. Actually I already have been using the rust-analyzer in the vscode. I don't understand why there is mis-formatted code but will double-check for next PR.
> 
> You could try in VSCode: Settings (ctrl + ,) > search "format on save" > enable

Done. Thank you

**Pull request closed without merging**
