### PR TITLE
Rename executor/ blend.rs module to project.rs

### LINKED ISSUE #1034: Rename executor/ `blend.rs` module to `project.rs`
At the time I added `blend.rs` module, I didn't know that there already exists the keyword `project`.
Now, there's no reason to keep the name `blend`. we can simply rename `blend` to `project`.

* renaming in core/executor
* renaming in test-suite

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=4d2DPR7)

fixed #1034

### CODE REVIEW

**Comment by ever0de** [comment]
Check CI. Rust module names have not changed.

**Comment by panarch** [comment]
Welcome 👍 
It would be good to also find & replace `blend` text uses in source codes to `project`.

**Comment by panarch** [comment]
Everything looks nice!
To pass the gh actions, the only remaining one to run is `cargo fmt --all` in the root directory.
Then, all the gh actions will pass.

**Comment by SaumyaBhushan** [comment]
@panarch Its done . Thanks alot for the help .

**Review by panarch — APPROVED** [review]
Thanks a lot for the contribution 👍 👍 👍

**Pull request merged**
