### PR TITLE
Convert Generic Type Parameter to Associated Type

### LINKED ISSUE #483: Convert `Store` trait type from Generic Type Parameter to Associated Type
1. Remove `Debug` trait bound
2. Convert GTP to Associated Type

Expected change
```rust
pub trait Store<T: Debug> {
...
}
```
to
```rust
pub trait Store {
  type Key;

  ..
}
```

`Debug` trait bound looks not really necessary to be included.

### PR DESCRIPTION
**Pull request by ever0de**
resolved #483

### CODE REVIEW

**Comment by ever0de** [comment]
Is there a way to get the type of GStore out as an Associated Type...
Hmm, I'm thinking about it.

**Comment by ever0de** [comment]
<https://github.com/rust-lang/rust/issues/44265>

Shall I use this?
Stabilization is coming soon.

**Comment by panarch** [comment]
@ever0de Sure,
Wow, finally GAT is coming!!

**Comment by panarch** [comment]
ref. https://github.com/gluesql/gluesql/issues/483

**Pull request closed without merging**
