### PR TITLE
Add support for BETWEEN and NOT BETWEEN

### PR DESCRIPTION
**Pull request by ryanhossain9797**
Add support for `BETWEEN` queries

```sql
SELECT * FROM users WHERE age BETWEEN 20 AND 30 
```

```sql
SELECT * FROM users WHERE age NOT BETWEEN 20 AND 30 
```

### CODE REVIEW

**Comment by panarch** [comment]
Wow, it looks very good :)
I'm so glad of your contribution though the project does not have enough documentation yet.
In case of test case file, I like your choice.
GlueSQL should have a proper place to put `BETWEEN` like query test cases, but it doesn't have for now.
So, in current status, `tests/between.rs` looks good.
I'll add test case stuff by registering an another issue.

Then, only thing I'd like to mention is this,
```value 10 BETWEEN 20``` is enough to have this logic, ```10 <= value AND value <= 20```.
But current code includes
```sql
value 10 BETWEEN 20

min(10, 20) <= value AND value <= max(10, 20)
```
You don't need to concern the case ```20 BETWEEN 10```, this should simply be `false`.
Then, you can also simply `filter.rs` code you wrote.

**Review by panarch — CHANGES_REQUESTED** [review]
Wow, it looks very good :)
I'm so glad of your contribution though the project does not have enough documentation yet.
In case of test case file, I like your choice.
GlueSQL should have a proper place to put `BETWEEN` like query test cases, but it doesn't have for now.
So, in current status, `tests/between.rs` looks good.
I'll add test case stuff by registering an another issue.

Then, only thing I'd like to mention is this,
```value 10 BETWEEN 20``` is enough to have this logic, ```10 <= value AND value <= 20```.
But current code includes
```sql
value 10 BETWEEN 20

min(10, 20) <= value AND value <= max(10, 20)
```
You don't need to concern the case ```20 BETWEEN 10```, this should simply be `false`.
Then, you can also simply `filter.rs` code you wrote.

**Comment by panarch** [comment]
Oh, I just briefly searched `BETWEEN` use cases, like this https://www.postgresqltutorial.com/postgresql-between/
You have any cases which supports conversion from `BETWEEN 20 AND 10` to `BETWEEN 10 AND 20`?

**Comment by ryanhossain9797** [comment]
Apparently the behavior differs. I tried it out in W3School's Live Editor and it worked, However apparently it doesn't work on Postgres or MSSQL Server which I tested just now. So I'll go ahead and remove it.

**Comment by ryanhossain9797** [comment]
changes made
also addressed #57 and moved `between` test to `filter.rs`

**Review by panarch — APPROVED** [review]
Looks good! merging, thanks 👍

**Pull request merged**
