### PR TITLE
Impelment `redb` storage

### LINKED ISSUE #1250: Impelment `redb` storage
[redb](https://www.redb.org/post/2023/06/16/1-0-stable-release/) has released version 1.0.
Let's add storage.

### PR DESCRIPTION
**Pull request by parkma99**
close #1250

### CODE REVIEW

**Comment by parkma99** [comment]
Hello @panarch , I make a initial code for this issue.
Could you give me some suggestion for this code? If anything is good, I will fill all `todo` late.

**Comment by panarch** [comment]
@parkma99 This looks good start!
Once you setup test-suite, then you can see the progress by checking the number of passing tests.

for now, you only need to consider adding `generate_store_tests!`.
ref.
https://github.com/gluesql/gluesql/blob/a68764678dc869642b66072c1bb3da431b704c61/storages/memory-storage/tests/memory_storage.rs#L1-L24

**Comment by parkma99** [comment]
@panarch  Thanks, I will go on.

**Comment by lu-zero** [comment]
What happened to this PR?

**Pull request closed without merging**
