### PR TITLE
Native English changes to README.md for easier readability

### PR DESCRIPTION
**Pull request by noproto**

### CODE REVIEW

**Comment by noproto** [comment]
Also, need to change the colon after Store and StoreMut to a period, and "You can see current query supports in" to "You can see currently supported queries in".

**Comment by panarch** [comment]
Wow, thanks so much!

**Comment by panarch** [comment]
@noproto https://github.com/gluesql/gluesql/commit/a31b31a9eb6731d16601be47fbf49f0fc632e910
I also applied :) thanks!

**Comment by noproto** [comment]
@panarch Thanks for accepting, but I realized I made a few mistakes and corrected them in a second, final pull request.

**Pull request merged**
