### PR TITLE
upgrade to rust 1.61

### PR DESCRIPTION
**Pull request by earney**
This seems to work on ubuntu linux for me.  Can we get some people try this on other OS's?  (windows, mac, etc)?

### CODE REVIEW

**Comment by ever0de** [comment]
스크린샷 2022-05-21 오전 10 24 09

If the version of clippy is specified, it seems to be available(v1.61).

**Comment by earney** [comment]
setting to draft until clippy 1.61 is released.

**Comment by ever0de** [comment]
https://github.com/rust-lang/rust-clippy/releases/tag/rust-1.61.0

It's been released and I think it's good to open it

**Review by ever0de — APPROVED** [review]
Thanks 👍

**Pull request merged**
