### PR TITLE
Add examples for MemoryStorage

### LINKED ISSUE #398: Add examples for `MemoryStorage`
Current files in `examples` are focused on using `SledStorage`.
Users might want to know how to use `MemoryStorage`.

### PR DESCRIPTION
**Pull request by pythonbrad**
resolved #398

### CODE REVIEW

**Comment by ever0de** [comment]
If the work is not completed, how about using the Draft function?
<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request>

**Comment by pythonbrad** [comment]
> If the work is not completed, how about using the Draft function? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

I think that i don't understand very well the issue.

**Comment by panarch** [comment]
Thanks a lot!
And.. plz excuse for inconvenience. Currently.. `examples/` directory is not being tested by GitHub Action and also not testable by `cargo run --example {example_name}`.
There is a plan to split root Cargo.toml into root and `gluesql/` binary package workspace.
This will be fixed (currently it is not high priority so it might take several weeks), then you will be able to work on it again.

**Comment by pythonbrad** [comment]
@panarch Ok, i understand.

**Comment by ever0de** [comment]
How about opening a PR and merging it? @panarch

**Comment by panarch** [comment]
@ever0de
The codes look all good, but recently we changed the directory from `/examples` to `/pkg/rust/examples` so.. after moving this example code to the new pkg directory, then there would be no issue to merge this.
Could you have a mind to do this? @pythonbrad

**Comment by ever0de** [comment]
Long time no see, can I open a PR? (Change Draft to Ready for review)

**Review by ever0de — APPROVED** [review]
Looks good! Thanks

**Review by panarch — APPROVED** [review]
Thanks a lot for the contribution :D Looks nice

**Pull request merged**
