### PR TITLE
Add `UINT32`, `UINT64` and `UINT128` data types

### PR DESCRIPTION
**Pull request by ChobobDev**

### CODE REVIEW

**Comment by ChobobDev** [comment]
I think I am ready for review

**Review by panarch — CHANGES_REQUESTED** [review]
I'd really appreciate the work you've done. Awesome!
Before the merge, could you add a few more tests to fill the remaining coverage?

image
https://github.com/gluesql/gluesql/pull/1019#issuecomment-1328000164

You can only care "New" lines

**Comment by ChobobDev** [comment]
I have made changes, thank you for the review :)

**Review by panarch — APPROVED** [review]
Thanks a lot for the contribution.
Looks all great!
Let's ship these features to the main 👍

**Pull request merged**
