### PR TITLE
 Add unit tests for data/value/literal.rs

### PR DESCRIPTION
**Pull request by pythonbrad**
Add a test case for the function below.
try_from_literal
try_cast_from_literal
TryFrom

Linked to the issue #425

### CODE REVIEW

**Comment by pythonbrad** [comment]
This pull request is incomplete. The tests that i commented, i don't not how to pass it.

**Comment by ever0de** [comment]
Did you know that Cargo clippy exists?
<https://github.com/rust-lang/rust-clippy>

It acts similar to lint, which catches unnecessary clones or unnecessary things in your code.

If you are using the cargo package manager, try the command `cargo clippy --all-features --all-targets -- -D warnings`.
We will provide you with a solution.

**Comment by pythonbrad** [comment]
@ever0de I think that it is good now.

**Review by panarch — APPROVED** [review]
Thanks so much!
All looks nice, merging 👍

**Pull request merged**
