### PR TITLE
Add `Exp`, `Ln`, `Log2`, `Log10`

### LINKED ISSUE #272: Support `exp`, `ln`, `log2`, `log10`
# :rocket: Feature request 
Support some basic functions, `exp`, `ln`, `log2`, `log10` to allow users to implement basic mathematical concepts in queries.

### `Exp`
```sql
SELECT EXP(2.0) AS "Exp";
```
|Exp|
|-----|
| 7.38905|

### `ln`
```sql
SELECT LN(2.0) AS "ln";
```
|ln|
|-----|
|0.6931471805599453|

### `log2`
```sql
SELECT log2(64.0) AS "log2";
```
|log2|
|-----|
|6.0000000000|

### `log10`
```sql
SELECT log10(1000) AS "log10";
```
|log10|
|-----|
|3|

### PR DESCRIPTION
**Pull request by heka1024**
Motivation:
`GlueSQL` currently lacks some basic functions. This pull request creates some basic functions, like `exp` and `log10`.

Modifications:
- Add `Exp`, `Ln`, `Log2`, `Log10` in `Function`

Result:
- Closes #272.
- Users can implement basic mathematical concepts in queries

### CODE REVIEW

**Comment by panarch** [comment]
Except for removing `PRIMARY KEY` ones, everything else looks perfect.

After finishing this, how about doing this issue? :)
* https://github.com/gluesql/gluesql/issues/308

**Comment by heka1024** [comment]
@panarch I Resolve conflicts and remove `PRIMARY KEY` on test. Can you check it once again?

**Comment by panarch** [comment]
@heka1024 Everything looks good, let's run quick `cargo fmt` and merge it into the main!

**Review by panarch — APPROVED** [review]
Awesome!! Thanks a lot 👍 👍 👍

**Pull request merged**
