### PR TITLE
feat: fmt list and map

### PR DESCRIPTION
**Pull request by Mehrbod2002**
fixes: #1220 
fix fmt on list and map Value and tests added

### CODE REVIEW

**Comment by Mehrbod2002** [comment]
@ever0de Look out for the tests's result .

**Comment by Mehrbod2002** [comment]
@ever0de Sometime HashMap switch the entries

**Comment by Mehrbod2002** [comment]
@ever0de Please re-run the workflows

**Review by panarch — CHANGES_REQUESTED** [review]
Oh sorry for the late review.

the current code will generate
```rust
let actual = Value::List(vec![Value::I32(1), Value::I32(2), Value::Str("hello".to_owned())]);
let expected = "[1,2,hello]";
```
that the string "hello" is not wrapped by `"`.

to fix this, we actually don't need to implement stringify by yourself.
we can use it from serde.
https://github.com/gluesql/gluesql/blob/0e13939662f6acac7091e96943ed93fed3f05e5d/core/src/data/value/json.rs#L53-L58

and that `serde_json::Value` implements `Display` so we can use it.

**Comment by Mehrbod2002** [comment]
@panarch you can review it .

**Review by panarch — APPROVED** [review]
Looks all nice 👍 
Thanks a lot for the contribution!

**Pull request merged**
