### PR TITLE
INSERT tests and fixes

### PR DESCRIPTION
**Pull request by KyGost**
Resolve: #197
Resolve: #190
Resolve: #189

### CODE REVIEW

**Comment by panarch** [comment]
I really appreciate on this work, thanks! solving three insertion issues.
Could you request review by making an independent pr per each issue?
For me, reviewing multiple contexts at the same time really requires much more effort to do look around.

**Comment by KyGost** [comment]
Please see it as improving insertion code and adding better tests and just also solving some bugs at the same time as that is what this is.

**Comment by KyGost** [comment]
Oh oops I didn't push my recent changes

**Comment by KyGost** [comment]
Why are these in this PR?!?!?!
Also I forgot to remove a test `println`, fixing now.

**Comment by panarch** [comment]
Oh.. now I see that..
Ok, this is really too much for me to do review at once.
* Resolve: #197 
* Resolve: #190
* Resolve: #189

These are independent issues, if you can split this PR into three, then I can fastly review one by one.
However, I'm not sure I can do review for this one.

**Comment by KyGost** [comment]
Please, once again, ignore the fixes.

This is a rewrite of how we compile rows and insert data.

**Comment by panarch** [comment]
Closing PRs which are merged and working well in the fork.

**Pull request closed without merging**
