### PR TITLE
cast 255 as int8, should return an error, but returns 127 instead (resolves issue #545)

### PR DESCRIPTION
**Pull request by earney**
Here's the error I found (this should probably produce an error, not insert 127 into an int(8) field).

```
gluesql> create table myi8 (id int(8));
gluesql> insert into myi8 values (1);
1 row inserted

gluesql> select cast(255 as int(8)) from myi8;
╭─────────────────────╮
│ CAST(255 AS INT(8)) │
╞═════════════════════╡
│ 127                 │
╰─────────────────────╯
gluesql>
```

This PR (resolves issue #545) implements the following result:

```
luesql> select cast(255 as int(8)) from dual;
[error] literal cast failed to Int(8): 255
```

### CODE REVIEW

**Comment by earney** [comment]
If the code looks good, I can look into converting the other (*, Literal::Number) cases so that they rely on BigDecimal to do the heavy lifting to convert from bigdecimal to i8, i64, f64, etc.

**Comment by earney** [comment]
resolves issue #545

**Comment by ever0de** [comment]
> resolves issue #545

This phrase should be at the top of your PR conversation. 👍 

e.g) <https://github.com/gluesql/gluesql/pull/512>
image

**Comment by earney** [comment]
This PR is still officially a draft, but I would like to receive comments about it.  I believe we can use the same basic code for other number types (int, float, decimal), and let bigdecimal do the heavy lifting by using bigdecimals to_i8, to_i64, to_f64 functions to convert the bigdecimal to the appropriate data type.   I am also looking at implementing solutions for i32, i128, and the unsigned versions (u8, u32, u64, and u128), in which the cast function would need code for each data type.

**Pull request merged**
