### PR TITLE
support execute_async

### PR DESCRIPTION
**Pull request by 24seconds**
Hello, while I'm using gluesql as a database (MemoryStorage),   

### Motivation
I found that glue blocks current thread until the execution is finished. For me, I need asynchronous execute function, not blocking one. So I wrote some code to support it.

### Question
I saw so many test cases are written in this repo. So I also think I should write a test but I don't know where to start. Could you give me some guide? Thank you!

### CODE REVIEW

**Comment by 24seconds** [comment]
After the guide, I wrote the test in examples/api_usage.rs.  
While doing that, I found 2 things and modified them with help from taehoon.

- mutable_api has some bug. It doens't run rest sqls, insert, drop etc. So I make them run in for loop
- In the glue.rs, plan function uses `block_on` internal. After talk with him, I changed this function as asynchronous

**Comment by 24seconds** [comment]
Added dedicated test for `execute_async`. Checked using tarpualin and it's 100% for glue.rs file.

**Review by panarch — APPROVED** [review]
Awesome 👍 
Thanks!!

**Review by ever0de — APPROVED** [review]
👍

**Pull request merged**
