### PR TITLE
Issue 82

### PR DESCRIPTION
**Pull request by willy610**
Just two lines changed (old 158 replaced and 196 deleted)

Rest diff is due to rustfmt

### CODE REVIEW

**Comment by panarch** [comment]
related to https://github.com/gluesql/gluesql/issues/82

**Comment by panarch** [comment]
similar with https://github.com/gluesql/gluesql/pull/87
Can you remove unrelated commits except for this one (#82)?

When you work on multiple issues at the same time, you can use different branches.

**Comment by panarch** [comment]
https://github.com/gluesql/gluesql/pull/112

@willy610 Could you clean up those commits..?
You need to make it into a single commit like the link above.

And you don't need to mention the issue number in commit message.
making a full sentence using starting with present verb is enough.

**Comment by willy610** [comment]
Sorry,
I’m also irritated on this but I don’t know how to process it.

You say 'clean up’. Some button in the WEB-interface or some Button in the GitHub Desktop.



> On 2020-11-14, at 18:30, Taehoon Moon <notifications@github.com> wrote:
> 
> 
> #112
> 
> @willy610 Could you clean up those commits..?
> You need to make it into a single commit like the link above.
> 
> And you don't need to mention the issue number in commit message.
> making a full sentence using starting with present verb is enough.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-----------------------------
Willy Svenningsson
Johannas Vag 28
S-425 42 Hisings Karra
Sweden
+46 0768 22 20 26
willy@fager.st

**Comment by panarch** [comment]
@willy610 You can think about cleaning up as very simple.

Fortunately, the code changes you did for this PR is not that too many.
So my recommendation is this,
1. pull the current main branch
2. apply your work (manually)
3. add PR

This is not related to GitHub specific functions.

**Comment by willy610** [comment]
Dear Friend,
I have just deleted my fork of gluesql!

I have decided to take a pause because I got a little bit frustrated
for not making contributions the way bot you and I want.
I have been struggling with iterators, contexts, debugging etc and
I think my abilities designing/writing code in that complex patterns are limited.

I start looking into this project when I understand it was possible to get 
a fast and memory safe SQL-engine as a tool actually. Education or whatever.
But also service time on 20 seconds due to subqueries triggered my involvement.

I really appreciate the work done so far. Full executor. And instructive solutions.

Of course I will follow the issues and issue list and probably do some off-line
pretty print of select and tool for interactive SQL and import of CSV.
Just for fun.

And also experiment with another kind of ’context'

But I think we somehow stay in touch

Kindly,willy

> On 2020-11-14, at 18:30, Taehoon Moon <notifications@github.com> wrote:
> 
> 
> #112
> 
> @willy610 Could you clean up those commits..?
> You need to make it into a single commit like the link above.
> 
> And you don't need to mention the issue number in commit message.
> making a full sentence using starting with present verb is enough.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-----------------------------
Willy Svenningsson
Johannas Vag 28
S-425 42 Hisings Karra
Sweden
+46 0768 22 20 26
willy@fager.st

**Comment by panarch** [comment]
@willy610 
Sad to hear that, but feel free to participate again whenever you want to.

And I'll also request you to run benchmark test after GlueSQL has an index support.
Current stage, due to lack of index support, GlueSQL may show quite slow performance which requires index.

Most of execution codes depend on iterator and I also understand it can be quite tough to see at first.
And... recently I was struggling with more tough ones.. `Stream`... it was quite.. beyond the `Iterator`.
Those are something... painful to get used to but after once we overcome then... very... very powerful.

Hope you join again in someday, stay in touch!

Best,
Taehoon

**Comment by willy610** [comment]
Hello again, Taehoon

Just for the record, in order to avoid to much parallel work

Can’t stop try to implement a good, flexible and almost full join.
The whole idea on Relational Database is relation between tables!

Working off line towards downloaded published source. No forks here. Yet.

Kindly,
 willy

> On 2020-11-17, at 07:57, Taehoon Moon <notifications@github.com> wrote:
> 
> 
> @willy610
> Sad to hear that, but feel free to participate again whenever you want to.
> 
> And I'll also request you to run benchmark test after GlueSQL has an index support.
> Current stage, due to lack of index support, GlueSQL may show quite slow performance which requires index.
> 
> Most of execution codes depend on iterator and I also understand it can be quite tough to see at first.
> And... recently I was struggling with more tough ones.. Stream... it was quite.. beyond the Iterator.
> Those are something... painful to get used to but after once we overcome then... very... very powerful.
> 
> Hope you join again in someday, stay in touch!
> 
> Best,
> Taehoon
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-----------------------------
Willy Svenningsson
Johannas Vag 28
S-425 42 Hisings Karra
Sweden
+46 0768 22 20 26
willy@fager.st

**Comment by panarch** [comment]
Ok, I'll look forward to see the work 👍

**Pull request closed without merging**
