### PR TITLE
Add SharedMemoryStorage to the src documentation comment

### PR DESCRIPTION
**Pull request by kim-seo-hyun**
Add SharedMemoryStorage to the src documentation comment

image

### CODE REVIEW

**Review by 24seconds — APPROVED** [review]
Because this is quite simple pr, LGTM.
Thank you for the first pr!

**Comment by ever0de** [comment]
ref #639

**Review by ever0de — APPROVED** [review]
Looks good 👍

**Comment by ever0de** [comment]
Please run `cargo fmt` thanks!

**Comment by 24seconds** [comment]
Check that All the github action passed. Let me merge it 

Is it okay?
cc: @panarch

**Pull request merged**
