### PR TITLE
Support Plus(+) and Minus(-) signs in WHERE

### PR DESCRIPTION
**Pull request by yejihan-dev**
This pull request resolves issue #101 by supporting unary operations of Value. Specific modifications are the following.
- value.rs & evaluated.rs: Functions to evaluate unary operations of the expression were added.
- mod.rs: Expressions now handle unary operations.
- test.rs: Two test cases to check if WHERE supports plus(+) and minus(-) signs were added.

### CODE REVIEW

**Review by panarch — CHANGES_REQUESTED** [review]
Awesome!
I'm late to review, I was on a trip for the last two days and just got back home today.
Looks very good and I can only see a few things to request.
I need to spend some hours on this so I will write a review back until tomorrow, Saturday.

Before starting, can you please merge current commits into a single commit?

It's ok to split into several commits if they have independent changes, but it looks there's not enough reason to have 4 commits on this.
git force push and git stash might be helpful on this kind of merging work.

**Comment by yejihan-dev** [comment]
@panarch Sure, I will merge all commits into one by this afternoon. If I finish combining all commits, should I make a new pull request?

**Comment by panarch** [comment]
@yejihan-dev It's just all up to you, making a new pr or using this thread, both are ok :)

**Comment by yejihan-dev** [comment]
@panarch Oh, then I will close this one and make up new request!

**Pull request closed without merging**
